package com.xiaoACE.ssm.entity.model;

import java.util.Date;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysuser.id
     *
     * @mbg.generated Fri Oct 14 09:24:44 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysuser.account
     *
     * @mbg.generated Fri Oct 14 09:24:44 CST 2022
     */
    private String account;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysuser.password
     *
     * @mbg.generated Fri Oct 14 09:24:44 CST 2022
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysuser.name
     *
     * @mbg.generated Fri Oct 14 09:24:44 CST 2022
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysuser.job
     *
     * @mbg.generated Fri Oct 14 09:24:44 CST 2022
     */
    private String job;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysuser.rights
     *
     * @mbg.generated Fri Oct 14 09:24:44 CST 2022
     */
    private String rights;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysuser.roleId
     *
     * @mbg.generated Fri Oct 14 09:24:44 CST 2022
     */
    private String roleid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysuser.deptId
     *
     * @mbg.generated Fri Oct 14 09:24:44 CST 2022
     */
    private String deptid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysuser.createUserId
     *
     * @mbg.generated Fri Oct 14 09:24:44 CST 2022
     */
    private String createuserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysuser.createTime
     *
     * @mbg.generated Fri Oct 14 09:24:44 CST 2022
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysuser.updateUserId
     *
     * @mbg.generated Fri Oct 14 09:24:44 CST 2022
     */
    private String updateuserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysuser.updateTime
     *
     * @mbg.generated Fri Oct 14 09:24:44 CST 2022
     */
    private Date updatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysuser.del
     *
     * @mbg.generated Fri Oct 14 09:24:44 CST 2022
     */
    private Boolean del;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysuser.enable
     *
     * @mbg.generated Fri Oct 14 09:24:44 CST 2022
     */
    private Boolean enable;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysuser.id
     *
     * @return the value of sysuser.id
     *
     * @mbg.generated Fri Oct 14 09:24:44 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysuser.id
     *
     * @param id the value for sysuser.id
     *
     * @mbg.generated Fri Oct 14 09:24:44 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysuser.account
     *
     * @return the value of sysuser.account
     *
     * @mbg.generated Fri Oct 14 09:24:44 CST 2022
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysuser.account
     *
     * @param account the value for sysuser.account
     *
     * @mbg.generated Fri Oct 14 09:24:44 CST 2022
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysuser.password
     *
     * @return the value of sysuser.password
     *
     * @mbg.generated Fri Oct 14 09:24:44 CST 2022
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysuser.password
     *
     * @param password the value for sysuser.password
     *
     * @mbg.generated Fri Oct 14 09:24:44 CST 2022
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysuser.name
     *
     * @return the value of sysuser.name
     *
     * @mbg.generated Fri Oct 14 09:24:44 CST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysuser.name
     *
     * @param name the value for sysuser.name
     *
     * @mbg.generated Fri Oct 14 09:24:44 CST 2022
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysuser.job
     *
     * @return the value of sysuser.job
     *
     * @mbg.generated Fri Oct 14 09:24:44 CST 2022
     */
    public String getJob() {
        return job;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysuser.job
     *
     * @param job the value for sysuser.job
     *
     * @mbg.generated Fri Oct 14 09:24:44 CST 2022
     */
    public void setJob(String job) {
        this.job = job == null ? null : job.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysuser.rights
     *
     * @return the value of sysuser.rights
     *
     * @mbg.generated Fri Oct 14 09:24:44 CST 2022
     */
    public String getRights() {
        return rights;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysuser.rights
     *
     * @param rights the value for sysuser.rights
     *
     * @mbg.generated Fri Oct 14 09:24:44 CST 2022
     */
    public void setRights(String rights) {
        this.rights = rights == null ? null : rights.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysuser.roleId
     *
     * @return the value of sysuser.roleId
     *
     * @mbg.generated Fri Oct 14 09:24:44 CST 2022
     */
    public String getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysuser.roleId
     *
     * @param roleid the value for sysuser.roleId
     *
     * @mbg.generated Fri Oct 14 09:24:44 CST 2022
     */
    public void setRoleid(String roleid) {
        this.roleid = roleid == null ? null : roleid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysuser.deptId
     *
     * @return the value of sysuser.deptId
     *
     * @mbg.generated Fri Oct 14 09:24:44 CST 2022
     */
    public String getDeptid() {
        return deptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysuser.deptId
     *
     * @param deptid the value for sysuser.deptId
     *
     * @mbg.generated Fri Oct 14 09:24:44 CST 2022
     */
    public void setDeptid(String deptid) {
        this.deptid = deptid == null ? null : deptid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysuser.createUserId
     *
     * @return the value of sysuser.createUserId
     *
     * @mbg.generated Fri Oct 14 09:24:44 CST 2022
     */
    public String getCreateuserid() {
        return createuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysuser.createUserId
     *
     * @param createuserid the value for sysuser.createUserId
     *
     * @mbg.generated Fri Oct 14 09:24:44 CST 2022
     */
    public void setCreateuserid(String createuserid) {
        this.createuserid = createuserid == null ? null : createuserid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysuser.createTime
     *
     * @return the value of sysuser.createTime
     *
     * @mbg.generated Fri Oct 14 09:24:44 CST 2022
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysuser.createTime
     *
     * @param createtime the value for sysuser.createTime
     *
     * @mbg.generated Fri Oct 14 09:24:44 CST 2022
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysuser.updateUserId
     *
     * @return the value of sysuser.updateUserId
     *
     * @mbg.generated Fri Oct 14 09:24:44 CST 2022
     */
    public String getUpdateuserid() {
        return updateuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysuser.updateUserId
     *
     * @param updateuserid the value for sysuser.updateUserId
     *
     * @mbg.generated Fri Oct 14 09:24:44 CST 2022
     */
    public void setUpdateuserid(String updateuserid) {
        this.updateuserid = updateuserid == null ? null : updateuserid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysuser.updateTime
     *
     * @return the value of sysuser.updateTime
     *
     * @mbg.generated Fri Oct 14 09:24:44 CST 2022
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysuser.updateTime
     *
     * @param updatetime the value for sysuser.updateTime
     *
     * @mbg.generated Fri Oct 14 09:24:44 CST 2022
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysuser.del
     *
     * @return the value of sysuser.del
     *
     * @mbg.generated Fri Oct 14 09:24:44 CST 2022
     */
    public Boolean getDel() {
        return del;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysuser.del
     *
     * @param del the value for sysuser.del
     *
     * @mbg.generated Fri Oct 14 09:24:44 CST 2022
     */
    public void setDel(Boolean del) {
        this.del = del;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysuser.enable
     *
     * @return the value of sysuser.enable
     *
     * @mbg.generated Fri Oct 14 09:24:44 CST 2022
     */
    public Boolean getEnable() {
        return enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysuser.enable
     *
     * @param enable the value for sysuser.enable
     *
     * @mbg.generated Fri Oct 14 09:24:44 CST 2022
     */
    public void setEnable(Boolean enable) {
        this.enable = enable;
    }
}