package com.xiaoACE.ssm.entity.mapper;

import com.xiaoACE.ssm.entity.model.User;

import java.util.List;
import java.util.Map;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysuser
     *
     * @mbg.generated Fri Oct 14 09:24:44 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysuser
     *
     * @mbg.generated Fri Oct 14 09:24:44 CST 2022
     */
    int insert(User row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysuser
     *
     * @mbg.generated Fri Oct 14 09:24:44 CST 2022
     */
    int insertSelective(User row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysuser
     *
     * @mbg.generated Fri Oct 14 09:24:44 CST 2022
     */
    User selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysuser
     *
     * @mbg.generated Fri Oct 14 09:24:44 CST 2022
     */
    int updateByPrimaryKeySelective(User row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysuser
     *
     * @mbg.generated Fri Oct 14 09:24:44 CST 2022
     */
    int updateByPrimaryKey(User row);

    //登录
    User selectUserByAccountAndPassword(Map<String,Object>map);

    //列出所有用户(被删除的除外)
    List<User> listAllUser();

    //搜索指定用户(被删除的除外)
    List<User> getUserListByInput(String value);

    //根据账户查找用户
    User selectUserByAccount(String account);

    //生产环境上的删除(flag)
    int updateDelFlagByPrimaryKey(Integer id);



}